/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class UserSessionSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'externalUserId', 'id', 'isActive', 'token'] as const
  $columns = UserSessionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare externalUserId: number
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare isActive: boolean | null
  @column()
  declare token: string
}
